audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  silence_threshold: 0.01
  silence_duration: 1.5
  max_recording_duration: 15.0
  device_index: null

speaker_verification:
  enabled: true
  password: "robótica"
  accepted_variants: ["robotica"]
  session_timeout_sec: 60.0

feedback:
  enable_tts: true
  tts_engine: "piper"
  tts_piper_model: "/home/arizbeth/8_semestre/voice_to_abb_ws/piper_voices/es_ES_davefx_medium/es_ES-davefx-medium.onnx"
  tts_piper_config: "/home/arizbeth/8_semestre/voice_to_abb_ws/piper_voices/es_ES_davefx_medium/es_ES-davefx-medium.onnx.json"
  #tts_piper_model: "/home/zuriel_tov/Voice/voice_to_abb/models/es_ES-davefx-medium.onnx"
  #tts_piper_config: "/home/zuriel_tov/Voice/voice_to_abb/models/es_ES-davefx-medium.onnx.json"
  tts_language: "es"
  tts_rate: 0
  tts_listen_guard_sec: 0.25
  verbose_feedback: false
  speak_examples_on_start: false

whisper:
  model_size: "base"
  device: "cpu"
  compute_type: "int8"
  language: "es"
  beam_size: 5

llama_cpp:
  model_path: "/home/arizbeth/8_semestre/voice_to_abb_ws/models/llama3.2-3b-q4.gguf"
  #model_path: "/home/zuriel_tov/Voice/voice_to_abb/models/llama3.2-3b-q4.gguf"
  temperature: 0.1
  max_tokens: 512
  n_ctx: 2048
  n_threads: 4

robot:
  actions:
    - move_joint
    - open_gripper
    - close_gripper
    - move_home
    - run_sequence
    - stop
    - pick
    - rotate_joint
  sequences:
    - id: home
      description: "Move robot to home position"
    - id: open_gripper
      description: "Open gripper"
    - id: close_gripper
      description: "Close gripper"
    - id: perception_pose
      description: "Move to perception pose"
    - id: classify_objects
      description: "Move to perception pose and wait for classified detections"
  object_classes: ["cube", "cylinder", "hexagon", "toroid", "apple"]
  joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7"]
  cartesian_axes: ["x", "y", "z", "roll", "pitch", "yaw"]
  units:
    angles: "degrees"
    distances: "meters"
    speed: "percentage"

logging:
  level: "INFO"
  log_to_file: false
  log_file: "logs/robot_voice.log"
  show_timestamps: true
