sensors:
  - realsense_pointcloud

octomap_frame: base_link
octomap_resolution: 0.03
max_range: 1.5

realsense_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /camera/camera/depth/color/points
  max_range: 1.5
  point_subsample: 2
  padding_offset: 0.03
  padding_scale: 1.0
  max_update_rate: 2.0
  filtered_cloud_topic: /moveit/filtered_cloud
